# App Configuration
APP_NAME:
APP_ENV:
LOG_LEVEL:
SERVER_PORT:
READ_TIMEOUT_MS:
WRITE_TIMEOUT_MS:
APP_VERSION:

# Database Configuration
DB_NAME:
SSL_MODE:
DB_HOST:
DB_USER:
DB_PASSWORD:
DB_PORT:
DB_POOL_SIZE:
DB_READ_TIMEOUT:
DB_WRITE_TIMEOUT:
DB_CONNECTION_MAX_LIFETIME_MINUTE:

# Redis Configuration
CACHE_API_TIMEOUT: 5
CACHE_DB: 0
CACHE_DIAL_TIMEOUT: 2500
CACHE_HOST: localhost:6379
CACHE_IDLE_TIMEOUT: 2500
CACHE_INVALID_MX_LOOKUP_TTL_MINUTES: 2
CACHE_MX_LOOKUP_TTL_MINUTES: 2
CACHE_PASSWORD: secret
CACHE_POOL_SIZE: 20
CACHE_READ_TIMEOUT: 2500
CACHE_WRITE_TIMEOUT: 2500
CACHE_DELAY_DURATION: 50


