# App Configuration
APP_NAME: awesomeProjectCr
APP_ENV: development
LOG_LEVEL: DEBUG
SERVER_PORT: 8080
READ_TIMEOUT_MS: 2000
WRITE_TIMEOUT_MS: 2000
APP_VERSION: 1.0.0

# Database Configuration
DB_CONNECTION_MAX_LIFETIME_MINUTE: 5
DB_HOST: localhost
DB_NAME: redik
SSL_MODE: disable
DB_PASSWORD: postgres
DB_POOL_SIZE: 20
DB_PORT: 5432
DB_READ_TIMEOUT: 2500
DB_USER: postgres
DB_WRITE_TIMEOUT: 2500

# Redis Configuration
CACHE_API_TIMEOUT: 5
CACHE_DB: 0
CACHE_DIAL_TIMEOUT: 2500
CACHE_HOST: localhost:6379
CACHE_IDLE_TIMEOUT: 2500
CACHE_INVALID_MX_LOOKUP_TTL_MINUTES: 2
CACHE_MX_LOOKUP_TTL_MINUTES: 2
CACHE_PASSWORD: secret
CACHE_POOL_SIZE: 20
CACHE_READ_TIMEOUT: 2500
CACHE_WRITE_TIMEOUT: 2500
CACHE_DELAY_DURATION: 50

